all:
	javac Main.java

clean:
	rm -rf */*/*.class
	rm -rf */*.class
	rm -rf *.class

run:
	java Main

show: 
	echo "Models:" && ls Models && echo "Cards:" && ls Hearthstone/Cards && echo "Game:" && ls Hearthstone/Game && echo "Hero:" && ls Hearthstone/Hero && echo "Hero/HeroPower:" && ls Hearthstone/Hero/HeroPower

